name: Python application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set up Python 3.13.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.13.9
    - name: Install dependencies
      run: |
        make install
        
